### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by 0eeixl** [SistemasTecTlaxiaco/infografia-0eeixl#4]
[imfografia.docx](https://github.com/SistemasTecTlaxiaco/infografia-0eeixl/files/12544382/imfografia.docx)
Erick Armando Aguilar Garcia

**Comment by Alberto796** [comment]
REDACCION: 10/10%
exposición de ideas: 15/11%
organizacion de la informacion: 15/13%
uso de imagenes: 15/13%
presentacion visual: 15/11%
referencias: 15/9%
presentacion:15/13%
calificacion final: 16
calificado por el equipo de Jose Antonio rodriguez cruz

**Comment by josealfredo79** [comment]
Falta la calificacion no mayor a 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
